dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: yJ9OTvvFNv5hCHwjepdpq9x3Rz4G2cqafGliF+IXOYBQgfUsRCc7NTIska91g1cXT8m1QH+r19nwK5YEfwOL2xam3IbemF4kq4jSALpOV5gqeXVLVOUdGBeiaDSmf3bHFu1vHnpGFw0t+UPsna3Vtt/sNVZ3M0k19bopy9A7D0d2v/P+U2Osgv2jX4wRvs9+BQhqUwYhh7U1KYXYJzlHMZWMxr6Wrg0v4Ilx0POFp75BwK38Bhaetn2/fJjWqMbjUMGjm9yP59kzFOIk6NRxHYU4c8epygI9xGNBPZbF/FsDfi3IGs/K973cOV83J+r1zuogTnqFplGhCeFj8YJWIs3ST1vr+67F3uXGMnEx1Bh2+kFRg8GkBxqtlmr5Zbq3hvsbNdS0/aI6t2kWsL1JvAXA8PG+fcn6TGbCAXxV8BSeYXN0SainjgJjJaedAFDZqZ7SCEtSsWWEfYKCM50Dk8o6oGSX7uOLwB7laGQITGL58AaHbV9knecWsZRca+QAhDu5guN9uEyakq/5GiuHUPgssK0un+phVjhY0esu6TYj/wnrib25J2Zdkdx3pwXKCYAGxzU2b4LWq9rcFY/vIqZWlF0N1IQVRzjQWpPaOWJwG0LpxBchem3PczrrLyDe0Dgun4fB+ymD4WdnxSHT6nl3163O5RjRxpOLkE5jNKc=
